[project]
name = "Strave Headmap Chache"
requires-python = ">=3.11"

[tool.ruff]
target-version = "py311"
line-length = 119
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade
]
