@startuml

package strava {
    class Cache
    class StravaFetcher
    class CacheWarmer
}

package tile {
    struct GeoPoint
    class Tile
}

Cache -> Tile

CacheWarmer -> Cache
CacheWarmer -.> Tile
CacheWarmer -.> GeoPoint

StravaFetcher -> Cache
StravaFetcher -> Tile

Tile -> GeoPoint

@enduml