name: Docker Image Build and Push to registry

on:
  workflow_dispatch:

  push:
    tags: [v*]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          pip install pytest ruff
      - name: Lint with Ruff
        run: ruff .
      - name: Run tests
        run: pytest tests

  build:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: denisbondar/strava-heatmap-cache
          tags: |
            type=raw,value=latest
            type=pep440,pattern={{version}}
          labels: |
            maintainer=Denis Bondar <bondar.den@gmail.com>
            org.opencontainers.image.title=Strava Heatmap Cache

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}